.Dd September 12, 2009
.Dt vmdkinfo
.Os libvmdk
.Sh NAME
.Nm vmdkinfo
.Nd determines information about a VMware Virtual Disk (VMDK) file
.Sh SYNOPSIS
.Nm vmdkinfo
.Op Fl ahvV
.Va Ar source
.Sh DESCRIPTION
.Nm vmdkinfo
is a utility to determine information about a VMware Virtual Disk (VMDK) file
.Pp
.Nm vmdkinfo
is part of the
.Nm libvmdk
package.
.Nm libvmdk
is a library to support the VMware Virtual Disk (VMDK) format
.Pp
.Ar source
is the source file.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl a
shows allocation information
.It Fl h
shows this help
.It Fl v
verbose output to stderr
.It Fl V
print version
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# vmdkinfo -a file.vmdk
vmdkinfo 20090905 (libvmdk 20090905, libuna 20090901, libbfio 20090901)

Shortcut information:
.Dl        ...

.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh BUGS
Please report bugs of any kind to <forensics@hoffmannbv.nl> or on the project website:
http://libvmdk.sourceforge.net/
.Sh AUTHOR
These man pages were written by Joachim Metz.
.Sh COPYRIGHT
Copyright 2009-2010 Joachim Metz <jbmetz@users.sourceforge.net>.
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.Sh SEE ALSO
