from enum import Enum


class DiskType(Enum):
    DISK_TYPE_UNDEFINED=0
    DISK_TYPE_2GB_EXTENT_FLAT=1
    DISK_TYPE_2GB_EXTENT_SPARSE=2
    DISK_TYPE_CUSTOM=3
    DISK_TYPE_DEVICE=4
    DISK_TYPE_DEVICE_PARITIONED=5
    DISK_TYPE_MONOLITHIC_FLAT=6
    DISK_TYPE_MONOLITHIC_SPARSE=7
    DISK_TYPE_STREAM_OPTIMIZED=8
    DISK_TYPE_VMFS_FLAT=9
    DISK_TYPE_VMFS_FLAT_PRE_ALLOCATED=10
    DISK_TYPE_VMFS_FLAT_ZEROED=11
    DISK_TYPE_VMFS_RAW=12
    DISK_TYPE_VMFS_RDM=13
    DISK_TYPE_VMFS_RDMP=14
    DISK_TYPE_VMFS_SPARSE=15
    DISK_TYPE_VMFS_SPARSE_THIN=16


class ExtentType(Enum):
    EXTENT_TYPE_FLAT=1
    EXTENT_TYPE_SPARSE=2
    EXTENT_TYPE_VMFS_FLAT=3
    EXTENT_TYPE_VMFS_SPARSE=4
    EXTENT_TYPE_VMFS_RAW=5
    EXTENT_TYPE_VMFS_RDM=6
    EXTENT_TYPE_ZERO=7
